"""Populate and execute-ready weekly notebook content for the starter-data capstone."""
from pathlib import Path
import nbformat as nbf

ROOT = Path(__file__).resolve().parents[1]
NB = ROOT / "work" / "notebooks"
SETUP = """from pathlib import Path\nimport sys\nROOT = Path.cwd()\nif not (ROOT / 'data').exists(): ROOT = ROOT.parent.parent\nsys.path.insert(0, str(ROOT / 'work' / 'scripts'))\nfrom sample_capstone import *\nimport pandas as pd\npd.set_option('display.max_columns', 20)\n"""

def md(text): return nbf.v4.new_markdown_cell(text)
def code(text): return nbf.v4.new_code_cell(text)
def write(name, cells):
    path=NB/name; old=nbf.read(path, as_version=4); old['cells']=cells; nbf.write(old, path)

def common(title, body, checks):
    return [md(f'# {title}\n\n**Scope:** bundled anonymized starter slice (30,000 content items across 32 pseudonymized clients).'), md(body), code(SETUP), code(checks), md('## Self-check\n\n- [x] Sections contain markdown reasoning and executable code.\n- [x] No client names, URLs, private queries, or credentials.\n- [x] Claims are observed, directional, and decision-support only.')]

def main():
    write('w01_research_question.ipynb', common('ML-02 — Research Question and Provisional Lane', '''## 1. My lane and why\n\nI chose **Refresh / Content Opportunity Scoring**. The output is a review queue, which fits the operational decision of where editors should spend scarce review time.\n\n## 2. Decision, action, and cost\n\nFor a content editor deciding which visible page to review first, this project ranks pages by observed decline-risk proxy. A false positive wastes review time; a false negative delays investigation of a potentially declining page.\n\n## 3. Careful words\n\nThis work measures associations in an anonymized release and produces decision-support rankings. It does not prove that an edit causes recovery or predict Google's algorithm.''', "df=load_frame()\nprint({'rows': len(df), 'clients': df.client_id.nunique(), 'declining_proxy_rate': round(df.is_declining_label.mean(),3), 'pages_with_300_plus_impressions': int((df.impressions_90d>=300).sum())})\ndf[['impressions_90d','sessions_90d','days_since_last_update']].describe().round(1)"))
    write('w02_ml_task_framing.ipynb', common('ML-03 — Frame Your Lane as an ML Task', '''## 1. Task type\n\nThis is binary classification used for **ranking**: estimate the probability that a page has the observed decline proxy, then rank the review queue.\n\n## 2. Target / proxy\n\n`is_declining_label = 1` when `trend_direction == 'down'`. This is an observed current-window proxy, not a future label; it is deliberately kept out of the features.\n\n## 3. Success metric\n\nPrimary: Precision@50 on a client holdout, because a review team can act on a finite top-K list. The positive base rate is shown alongside every metric.\n\n## 4. Unit of analysis\n\nOne row is one pseudonymized content item with trailing-90-day measurements.\n\n## 5. Why ML\n\nFreshness, visibility, position, CTR, engagement, and content context interact in ways a single threshold cannot express.''', "df=load_frame()\nprint(df[['content_id','client_id']].duplicated().sum(), 'duplicate page-client keys')\nprint(df[['trend_direction','is_declining_label']].value_counts().sort_index())"))
    write('w03_data_contract.ipynb', common('ML-04 — Search Intelligence Data Contract', '''## 1. Unit and window\n\nOne row is one content item, measured over a trailing 90-day window. The starter slice does not expose exact dates, so it supports a snapshot/proxy analysis rather than future-window forecasting.\n\n## 2. Field classification\n\nFeatures: visibility, position, freshness, safe content metadata, CTR, engagement and missingness indicators. Label: `is_declining_label`. Context: pseudonymous IDs, used only for splitting. Excluded: identifiers, label inputs (`trend_direction`, `trend_pct`), provider/model fields, and any product decision flags.\n\n## 3. Data limits\n\nMissingness is patterned by content type. Rates are percent values on a 0–100 scale; average position zero means no position data.''', "df=load_frame(); numeric,categorical=feature_columns()\nprint({'rows':len(df),'unique_pages':df.content_id.nunique(),'clients':df.client_id.nunique(),'duplicate_content_ids':int(df.content_id.duplicated().sum())})\nprint(df[['search_volume','word_count','avg_position']].isna().mean().round(3))\nprint(df.groupby('content_type', dropna=False)['search_volume'].apply(lambda s:s.isna().mean()).round(3) )"))
    write('w03_feature_leakage_check.ipynb', common('ML-05 — Feature Vector and Leakage Check', '''## 1. Feature vector\n\nNumeric features use median imputation; categorical features use most-frequent imputation and one-hot encoding. `has_keyword_context` exposes systematic missingness explicitly rather than silently treating it as zero.\n\n## 2. Leakage hunt\n\nThe label is built from `trend_direction`, itself derived from `trend_pct`; both are excluded. IDs are used only for the grouped split. No product scores or flags are used.\n\n## 3. Exclusions\n\n`provider_used` and `model_used` are not used: they are not necessary for the editorial decision and could encode collection practices rather than a generalizable signal.''', "df=load_frame(); numeric,categorical=feature_columns()\nprint('numeric:', numeric)\nprint('categorical:', categorical)\nprint('intersects label inputs:', set(numeric+categorical).intersection({'trend_direction','trend_pct'}))\nprint('intersects identifiers:', set(numeric+categorical).intersection({'content_id','client_id'}))"))
    write('w04_signal_audit.ipynb', common('ML-06 — Signal Audit', '''## 1. Distributions\n\nTraffic fields are heavy-tailed, so the modeling path uses log-transformed impression and session totals in addition to raw fields.\n\n## 2. Signal tests\n\nThe grouped summaries below are descriptive only. Each includes counts; no causal meaning is assigned.\n\n## 3. Practice implication\n\nVisibility and freshness are useful review context, but a page should not be changed automatically from any individual signal.''', "df=load_frame()\nfor col in ['impressions_90d','sessions_90d','days_since_last_update']:\n    print(col, df[col].quantile([.5,.9,.99]).round(1).to_dict())\nprint('\\nDecline proxy rate by freshness tier:')\nprint(df.groupby('freshness_tier',dropna=False).agg(n=('is_declining_label','size'),rate=('is_declining_label','mean')).round(3))\nprint('\\nDecline proxy rate by position tier:')\nprint(df.groupby('position_tier',dropna=False).agg(n=('is_declining_label','size'),rate=('is_declining_label','mean')).round(3))"))
    write('w04_baseline_score.ipynb', common('ML-07 — Baseline Action Score', '''## 1. Rule and reasons\n\nThe transparent rule prioritizes pages that are visible (≥300 impressions), stale (≥180 days since update), have low CTR (≤1%), or sit on pages two to three. Reason codes state which condition contributed.\n\n## 2. Top-20 review\n\nThe preview is deliberately public-safe: no page IDs, titles, clients, URLs, or queries. Manual review must assess topical relevance, business value, correctness, and whether a content change is warranted.''', "df=baseline_score(load_frame())\ntrain,test=split_frame(df)\nprint({'test_rows':len(test),'base_rate':round(test.is_declining_label.mean(),3),'baseline_precision_at_20':round(precision_at_k(test.is_declining_label,test.baseline_score,20),3),'baseline_precision_at_50':round(precision_at_k(test.is_declining_label,test.baseline_score,50),3)})\ntop=test.sort_values('baseline_score',ascending=False)[['baseline_score','baseline_reason','impressions_90d','ctr','avg_position','days_since_last_update']].head(20)\ntop"))
    write('w05_model.ipynb', common('ML-08 — Capstone Modeling Lane', '''## 1. Method and split\n\nLogistic regression is the readable comparator; random forest captures non-linear interactions. The held-out test set contains entire unseen pseudonymous clients, preventing row-level client memorization.\n\n## 2. Honest comparison\n\nEvery method is evaluated on the same client holdout and with the same Precision@K metric as the frozen baseline.\n\n## 3. Interpretation\n\nFeature importance must be inspected for plausibility. Strong performance is not evidence of causality.''', "metrics,split,test=run_models()\nprint(split)\nmetrics.round(3)\nprint('\\nLargest model-score errors (public-safe feature view):')\ntest.assign(error=(test.is_declining_label-test.model_probability).abs()).sort_values('error',ascending=False)[['is_declining_label','model_probability','impressions_90d','ctr','avg_position','days_since_last_update']].head(10)"))
    write('w06_validation_audit.ipynb', common('ML-09 — Validation and Claim Audit', '''## 1. Methodology questions\n\nA compelling search finding needs an observed label, clearly bounded population, and a validation split matching deployment. Cross-sectional comparisons cannot show that a refresh caused recovery.\n\n## 2. Final audit\n\nThis notebook uses a client holdout, reports base rate, excludes label-derived fields, and keeps predictions out-of-sample. The starter slice cannot support a time-forward claim because it supplies only trailing-window aggregates.\n\n## 3. Claim rewrite\n\nUnsafe: “Refreshing stale pages will improve Google rankings.”\n\nSafe: “In this anonymized starter slice, the model ranked pages with the decline proxy ahead of the baseline at the reported Precision@K; the ranked list is a candidate set for human review.”''', "metrics,split,test=run_models()\nprint(metrics[['method','precision_at_20','precision_at_50','base_rate']].round(3))\nprint({'label_inputs_excluded': True, 'ids_excluded_from_features': True, 'test_clients_unseen_in_train': True, 'future_outcome_claim': False})"))
    write('w07_action_playbook.ipynb', common('ML-10 — Content Action Playbook', '''## 1. Ranked actions\n\nReview the highest-scored pages first. A `visible_stale_low_ctr|model_risk` reason means the page is visible, stale, under-captures clicks by the rule, and also ranks highly under the learned proxy model.\n\n## 2. Human review and no-go list\n\nAn editor must inspect intent, factual accuracy, internal linking, SERP context, business priority, and possible measurement issues. The system must never auto-publish, remove pages, change titles, or claim causal impact.\n\n## 3. Monitoring\n\nRe-run after a new valid measurement window; investigate if Precision@50 falls materially, feature distributions shift, or editorial reviewers reject a large share of top recommendations.''', "metrics,split,queue=export_artifacts()\nprint(metrics.round(3))\nprint('Wrote public-safe files to work/outputs/ and work/figures/.')\nqueue.head(20)"))
    write('capstone.ipynb', common('Capstone — Refresh Opportunity Scoring', '''## Abstract\n\nThis project asks which visible content items an editor should review first. It uses the bundled anonymized FlyRank starter slice of 30,000 pseudonymized content items and a grouped client holdout. A transparent visibility-and-freshness baseline is compared with logistic regression and random forest models using a current-window decline proxy and Precision@K. The resulting metrics quantify out-of-sample ranking quality on the held-out clients, while the output is a public-safe, reason-coded review queue. This is directional decision support, not a prediction of Google's algorithm or evidence that editing causes recovery.\n\n## 1. Question\n\nFor editors deciding what to review first, rank visible pages by an observed decline-risk proxy.\n\n## 2. Data\n\nThe analysis uses `content_refresh_anonymized.csv`: one row per pseudonymized content item, 30,000 rows and 32 clients. IDs are split-only context; label-derived trend fields, provider/model fields, and any product flags are excluded.\n\n## 3. Methodology\n\nThe target is `trend_direction == down`; `trend_direction` and `trend_pct` are never features. Numeric values use median imputation; categoricals use most-frequent imputation plus one-hot encoding. The split holds out clients, and baseline/model metrics use the same test rows.\n\n## 4. Results\n\nThe executable table below is the source of truth for model-versus-baseline numbers.\n\n## 5. Limitations\n\nThis starter slice contains trailing-window aggregates rather than a full feature-to-future-outcome timeline. It cannot establish causal refresh impact, individual content quality, or Google's ranking factors.\n\n## 6. Ranked recommendations\n\nUse the highest-scored candidates as a manual editorial review queue; reason codes explain prioritization, not prescribed edits.\n\n## 7. Reproducibility and data credit\n\nRun this notebook top-to-bottom after `pip install -r requirements.txt`. Random state is 42. Built on the [FlyRank ML Internship dataset](https://flyrank.ai).\n\n## ML-12: employer-facing summary\n\nI built a reproducible content-review ranking workflow on anonymized search and engagement data. It compares a human-readable baseline with out-of-sample ML ranking and exports public-safe reason-coded recommendations. The result is a decision-support tool that keeps human editorial judgment in the loop.''', "metrics,split,queue=export_artifacts()\nprint(split)\nmetrics.round(3)\nqueue.head(20)"))

if __name__ == '__main__': main()
